### PR TITLE
Support alphabetical version aliases

### LINKED ISSUE #3: Does not support referencing versions by name
When using e.g. an LTS version by name in `.nvmrc` (such as `lts/dubnium`), one of the plugins dependencies, `sh-semver`, chokes:

```sh
/usr/local/bin/../Cellar/nodenv-nvmrc/1.0.1/bin/../node_modules/sh-semver/semver.sh: line 138: [: lts: integer expression expected
/usr/local/bin/../Cellar/nodenv-nvmrc/1.0.1/bin/../node_modules/sh-semver/semver.sh: line 142: [: lts: integer expression expected
/usr/local/bin/../Cellar/nodenv-nvmrc/1.0.1/bin/../node_modules/sh-semver/semver.sh: line 138: [: lts: integer expression expected
/usr/local/bin/../Cellar/nodenv-nvmrc/1.0.1/bin/../node_modules/sh-semver/semver.sh: line 142: [: lts: integer expression expected
/usr/local/bin/../Cellar/nodenv-nvmrc/1.0.1/bin/../node_modules/sh-semver/semver.sh: line 138: [: lts: integer expression expected
/usr/local/bin/../Cellar/nodenv-nvmrc/1.0.1/bin/../node_modules/sh-semver/semver.sh: line 142: [: lts: integer expression expected
[...]
nvmrc: no version satisfying `lts/dubnium' installed
```

### PR DESCRIPTION
**Pull request by lumaxis**
Closes #3 

Related to the discussion in https://github.com/nodenv/nodenv-aliases/pull/25#issuecomment-489733985 , I noticed that `nodenv-nvmrc` chokes when using a version in `.nvmrc` such as `lts/dubnium`.
When using `nodenv-aliases`, `nodenv` is able to handle these just fine from a `.node-version` but `nodenv-nvmrc` exists with an error code and shows a bunch of errors from `sh-semver` because it tries to compare the alphabetical version string agains a bunch of numbers.

This PR only adds the version expressions to the `versions` array that is passed to `sh-semver` if it contains only digits and periods.
The changes also change a couple assumptions about error cases so I had to adjust a few other tests.

### CODE REVIEW

**Comment by lumaxis** [comment]
Running the tests seems to fail when using `yarn` and Travis automatically runs the tests with `yarn` if a `yarn.lock` is detected.
Since all other `nodenv` projects seem to use `npm` and `package-lock.json` files, I made the switch here, too.

**Comment by ouchxp** [comment]
Thanks for the PR! It's great piece of work!

**Comment by lumaxis** [comment]
@ouchxp Any chance we can get a new release with this fix? 🙂

**Comment by jmoody** [comment]
Beat me to it @lumaxis  - anything we can do to help you release @ouchxp ?

**Comment by ouchxp** [comment]
Thanks for the reminder! I will try make a release tomorrow.

**Comment by ouchxp** [comment]
I have made a release and updated brew tap! Cheers!

**Comment by lumaxis** [comment]
Awesome, thanks! ✨

**Pull request merged**
